
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cn.thinkx.pms.connect.pmspaymentgate;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

import org.springframework.beans.BeanUtils;

import com.cn.thinkx.pms.base.utils.DateUtil;
import com.cn.thinkx.pms.base.utils.ReadPropertiesFile;
import com.cn.thinkx.pms.connect.entity.TxnPackageDTO;
import com.cn.thinkx.pms.connect.service.Java2TXNBusinessService;
import com.cn.thinkx.pms.connect.utils.ConnectConstant;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-02-25T15:48:21.551+08:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "PMSService",
                      portName = "PMSServicePort",
                      targetNamespace = "http://pms.thinkx.cn.com/PMSPaymentGate",
                      wsdlLocation = "wsdl/PMSPaymentGate.wsdl",
                      endpointInterface = "com.cn.thinkx.pms.connect.pmspaymentgate.PMSPaymentGateServicePortType")
                      
public class PMSPaymentGateServicePortTypeImpl implements PMSPaymentGateServicePortType {

	private Logger LOG = Logger.getLogger(getClass().getName());

	private Java2TXNBusinessService businessService;

	public SearchResponse search(SearchRequest input) {
		LOG.info("Executing operation search");
		SearchResponse response = new SearchResponse();
		TxnPackageDTO txnPackageDTO = new TxnPackageDTO();

		BeanUtils.copyProperties(response.getSearchResponseBody(), txnPackageDTO);
		Map<String, String> params = new HashMap<String, String>();
		params.put(ConnectConstant.TXN_TYPE, ReadPropertiesFile.getInstance().getProperty("PAY_GATE_SEARCH_TXN_TYPE", null));
		params.put(ConnectConstant.TXN_CHANNEL, ReadPropertiesFile.getInstance().getProperty("PAY_GATE_SEARCH_TXN_CHNL_ID", null));
		SearchResponseHeard responseHeard = new SearchResponseHeard();
		responseHeard.setResponseDate(DateUtil.convertCurrentDateTimeToString());
		responseHeard.setSeq(input.getSearchRequestHeard().getSeq());
		MessageBody body = new MessageBody();
		try {
			TxnPackageDTO txn = businessService.queryTransation(txnPackageDTO, params);
			if ("00".equals(txn.getRspCode())) {
				responseHeard.setStatus("SUCCESS");
				BeanUtils.copyProperties(txn, body);
			} else {
				responseHeard.setStatus("FAILUER");
			}
		} catch (Exception e) {
			responseHeard.setStatus("FAILUER");
		}
		response.setSearchResponseHeard(responseHeard);
		response.setSearchResponseBody(body);
		return response;
	}

	public void setBusinessService(Java2TXNBusinessService businessService) {
		this.businessService = businessService;
	}

}
