package com.cn.thinkx.pms.connect.pmspaymentgate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-02-25T15:48:21.739+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://pms.thinkx.cn.com/PMSPaymentGate", name = "PMSPaymentGateServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PMSPaymentGateServicePortType {

    @WebResult(name = "searchResponse", targetNamespace = "http://pms.thinkx.cn.com/PMSPaymentGate", partName = "output")
    @WebMethod(action = "http://pms.thinkx.cn.com/PMSPaymentGate/search")
    public SearchResponse search(
        @WebParam(partName = "input", name = "searchRequest", targetNamespace = "http://pms.thinkx.cn.com/PMSPaymentGate")
        SearchRequest input
    );
}
